### ISSUE TITLE
Activate License for Users who Opted Out

### ISSUE THREAD

**Issue by iconicwp** [Freemius/wordpress-sdk#95] opened 2016-09-28 14:44 UTC
Scenario:
- Install plugin.
- Opt out.
- Later decide to purchase, but I buy a license from an external source and get a license key via email.
- "Account" page is not accessible as I opted out, and there is no "Activate License" link in the plugins list.

**Comment by vovafeldman** [comment] 2016-10-14 14:28
@iconicwp thanks for the submission. Obviously, we'll make it work for that use case. For now, the workaround would be telling the customer to go to `/wp-admin/admin.php?page=freemius`, there, clicking on "Delete All Accounts" button:

![image](https://cloud.githubusercontent.com/assets/6830121/19390936/5f9d3664-91f8-11e6-9a66-44f4c82f8e0d.png)

This will clean-up the "memory" that the user has skipped the opt-in before. Now, if the user activates the premium version, he'll be prompted with the license key form. If not, guide the user to click the "Activate License" link from the plugins page:
![image](https://cloud.githubusercontent.com/assets/6830121/19391048/bf6cd694-91f8-11e6-80d1-8b08ccc34914.png)

**Comment by fajardoleo** [comment] 2016-11-11 15:37
Hi @iconicwp, I didn't manage to reproduce the issue, sorry. Could you please tell us what version of the SDK did you use? Please also send the link to the relevant plugin.

**Comment by vovafeldman** [comment] 2016-11-12 17:21
@fajardoleo maybe you can't reproduce it because we fixed the `has_premium_plan()` method to work correctly for non-opted-in users?

**Comment by fajardoleo** [comment] 2016-11-21 18:12
@vovafeldman, @iconicwp, I tested multiple plugins and still didn't manage to reproduce the issue. I guess I need additional details such as the relevant SDK version and the relevant plugin to test.

**Comment by vovafeldman** [comment] 2016-12-05 01:11
@iconicwp - @fajardoleo managed to reproduce it and it will be fixed with the upcoming release.

**Closed** 2017-01-09 00:54 UTC
Labels: bug
