### ISSUE TITLE
Option `fs_accounts`, which is very large, has the autoload flag set to `true`

### ISSUE THREAD

**Issue by daigo75** [Freemius/wordpress-sdk#519] opened 2021-10-01 16:57 UTC
# 🐞 bug report

**Behavior**:
A client reported that option `fs_accounts` has the `autoload` property set to `yes`. Apparently, that option is also large in size, so this automatic loading affects the performance significantly.

The autoload flag seems to be set by method `FS_Option_Manager::store()`, which uses property `FS_Option_Manager::$autoload`. Based on a quick inspection, that property is always set to `null`, which means that it defaults to true when function `update_option()` is called.

**The fix** could be as simple as setting the `autoload` property to `false`. That should prevent WordPress from unnecessarily loading the option.

**Versions**: (*)
 -  `Freemius SDK Version:` 2.4.2
 -  `WordPress Version:` 5.7.x
 -  `PHP Version:` 7.2-7.4

**Plugin / Theme**: (*)
 -  `Name:` Aelia Currency Switcher for WooCoommerce
 -  `Slug:` woocommerce-aelia-currencyswitcher
 -  `Freemius ID:` 6708

**Note**: this affects any plugin, or theme, using the WordPress SDK.

**Comment by lkraav** [comment] 2021-10-06 14:26
Probably duplicate of https://github.com/Freemius/wordpress-sdk/issues/400

**Comment by banago** [comment] 2022-01-11 07:32
And I have two of those. Not acceptable. This needs to be a transient, or at least not auto-loaded.

![options](https://user-images.githubusercontent.com/339914/148899761-9203776a-d809-48f9-a3e8-66b35c81c863.png)

**Comment by vovafeldman** [comment] 2022-01-19 16:42
Yep, as @lkraav mentioned this is a dup of #400

We are aware of the issue and will eventually address it (unfortunately, due to other priorities there's no ETA).

@banago I'm not sure how you can have two options with the same `option_name` in the same DB, so that's awkward. The option cannot be fully moved to a transient as it holds non-temporary data. There are more insights about the option in my comment [here](https://github.com/Freemius/wordpress-sdk/issues/400#issuecomment-744621554).

**Closed by vovafeldman** 2022-01-19 16:42 UTC

**Comment by vovafeldman** [comment] 2022-02-15 07:19
@skullo27 I wish it was as easy as setting the autoload to `false` - if that was the case we would have done that a long time ago. The thing is that we are storing all the settings in a single option record and some of the settings are required on every PHP load, so setting the autoload to `false` will not resolve it, the option will be loaded anyway but in a separate DB query (less performant).

**Comment by daigo75** [comment] 2022-02-15 12:57
@vovafeldman Perhaps it could make sense to store the settings used at every page load separately from the ones used less frequently?

**Comment by vovafeldman** [comment] 2022-02-15 14:13
That's the plan, @daigo75. To do so requires a full audit of the settings and making sure we don't break backward compatibility, it's a meaningful infrastructural change. We'll get there eventually.

**Comment by samuelbauer-io** [comment] 2023-09-12 09:43
@vovafeldman 1,5 years later now - Update? Autoload 250kb in my case and that's really not what supports sustainable wp dev. Thanks for your understanding.

Possibility: The plugin "Admin Menu Editor Pro" does apply compression to it's autoload value (optional; can be activated in settings).

**Comment by vovafeldman** [comment] 2023-09-12 10:28
@samuelbauer-io we are working on releasing a solution for it soon. You can follow the updates here https://github.com/Freemius/wordpress-sdk/issues/400
