### ISSUE TITLE
Freemius Notice Error — Multisite Testing

### ISSUE THREAD

**Issue by asharirfan** [Freemius/wordpress-sdk#217] opened 2018-02-08 08:07 UTC
**Actual Behavior**:
 -  `What is the issue? (*)`
I have a WordPress multisite setup where I am currently testing the feature/multi-site branch of Freemius. The plugin that I am testing Freemius with is WP Security Audit Log.

## Steps:

1. I added a *new website* with a *new admin* – this admin does not have access to network panel :no_entry_sign:

2. I opened the *dashboard* of the new website with new admin and this notice was present in the header: https://cl.ly/pP0V

3. The link in this notice is redirecting me to the plugin menu present in the network admin panel. This means that this link is intended for the super admins, but it is being shown to a site admin – don’t know if it’s intentional or a bug 🤔 

4. Then I opened the website dashboard with the super admin, clicked on the link, went to the account page and clicked on the *Opt-In* button present with the URL of the website in the Sites section.

5. After that, I visited the website again and this notice is still present – https://cl.ly/pOMH. This notice should not be appearing anymore, don’t you think?

**Freemius Status:** Freemius was already active with 5 sites license from the Network Dashboard.

**Versions**: (*)
 -  `Freemius SDK Version:` 2.0.0
 -  `WordPress Version:` 4.9.4
 -  `PHP Version:` 7.1.7

**Plugin / Theme**: (*)
 -  `Name:` WP Security Audit Log
 -  `Slug:` wp-security-audit-log
 -  `Freemius ID:` 94

**Additional Information**:
 -  `Browser Type: (*)` Google Chrome
 -  `Browser Version: (*)` 64.0.3282.140
 -  `OS: (*)` macOS Sierra v10.12.6

**Comment by vovafeldman** [comment] 2018-02-12 17:07
@asharirfan the admin notice issue is fixed now. Also, enriched the logic to work as follows:

When a new site is added to the network and the plugin is network activated: 
- If the super-admin opted-in for all -> auto opt-in the new site.
- If the super-admin skipped for all -> auto-skip the new site's opt-in.
- If the super-admin delegated for all -> delegate the connection to the site admin.
- If the super-admin mixed options:
   - If delegated at least one site, delegate the new one as well.
   - If didn’t delegate at all, it means that at least one site was skipped (otherwise, all sites were skipped or opted-in), so skip the opt-in for the new site.
- If the super-admin activated a license on all sites in the network -> try to activate automatically when possible:
   - If activated, great.
   - If can’t activate, the user can do that later from the network Account page

Please confirm that it's working on your end as expected.

**Comment by asharirfan** [comment] 2018-02-13 07:41
@vovafeldman Thanks for the update 🙌

## 🔥 Feedback from Testing

- I have set up a new multisite for testing, and I am stuck in a loop.
  - I **Network Activate** the plugin, Freemius asks for License.
  - I input the license key and click **Agree & Activate**.
  - The plugin is activated and I am redirected to the main website.
  - I go back to my **Network Panel** and I see this notice:

     > You are just one step away - Complete "WP Security Audit Log" Activation Now

### 🎯 From Robert:
- I used my old multisite for testing.
  - I installed the plugin and activated the plugin on all these sites:
    - wpwhitehat.com (network and site)
    - site1.wpwhitehat.com
  - I skipped this:
    - site2.wpwhitehat.com
  - Upon logging to site2.wpwhitehat.com I was greeted with this:

     > You are just one step away - Complete "WP Security Audit Log" Activation Now

  - If I click on the link in the notice, I get WordPress error page with this notice:

     > Sorry, you are not allowed to access this page.

  - ⚡️ When the super admin "Skips" a site, then the plugin should still be activated on that subsite (site2) but not opted-in. As if someone installed it on single site and chose not to opt-in to freemius. In such case, the plugin should still work as normal.

**Comment by vovafeldman** [comment] 2018-02-20 17:56
@asharirfan Robert's reported issue was fixed. Couldn't reproduce your issue, so let's discuss it tomorrow.

**Comment by WPWhiteSecurity** [comment] 2018-02-20 20:14
@vovafeldman just tested the latest version of the SDK and can confirm that the issue I reported is fixed. Thanks.

**Comment by vovafeldman** [comment] 2018-02-21 08:53
@asharirfan closing this for now (2nd issue was fixed, can't reproduce the 1st issue).

**Closed by vovafeldman** 2018-02-21 08:53 UTC
