### ISSUE TITLE
Freemius breaks quotes localization due to early call of get_plugin_data()

### ISSUE THREAD

**Issue by vovafeldman** [Freemius/wordpress-sdk#77] opened 2016-08-01 20:37 UTC
Seems like the call to `get_plugin_data()` triggers `_get_plugin_data_markup_translate()` which calls `load_plugin_textdomain()` too early.

**Solution:**
Option 1: Try calling `get_plugin_data()` with `$markup` and `$translate` equals `false`.
Option 2: If option 1 doesn't help, create a local copy of `get_plugin_data()` that doesn't call unnecessary core methods.

**Reference:**
https://wordpress.org/support/topic/freemius-integration-broke-localized-quotes
https://wordpress.org/support/topic/conflict-with-wp-to-twitter-1?replies=14

CC: @danieliser

**Comment by mundschenk-at** [comment] 2016-08-02 09:38
A small technical note: In the case of wp-Typography the problem is that the `run_wptexturize` filter is only evaluated on the first call to `wptexturize`. With the current Freemius implementation, this happens too early for other plugins to actually affect the filter.

**Comment by danieliser** [comment] 2016-08-02 15:12
@mundschenk-at: correct, both solutions #1 & 2 above should resolve that, please test it like so:

1. Open class-freemius.php
2. Search for function get_plugin_data()
3. Replace $plugin_data = get_plugin_data( $this->_plugin_main_file_path ); with $plugin_data = get_plugin_data( $this->_plugin_main_file_path, false, false );

Currenlty Freemius calls get_plugin_data too early without the false, false at the end. That in turn causes WP to call load_plugin_textdomain. During that call is when wptexturize is called.

So setting to false, false should prevent those extra function calls and prevent wptexturize from being called at all. It is only called as a result of _get_plugin_data_markup_translate which is due to the second two arguments of get_plugin_data not being false.

Hope that helps.

**Comment by mundschenk-at** [comment] 2016-08-02 15:20
Sorry, I should have made myself more clear. I wasn't looking for a solution, but noting that there are two separate issues involved (both fixed by the same patch). 

265425d7a89307361fd3228587892a95b7e472e7 certainly works, as I've already confirmed for @vovafeldman  in the originating thread in the WP plugin forums.

**Closed** 2016-08-17 02:39 UTC
Labels: bug
