### ISSUE TITLE
Fatal GetResult() error when Freemius `id` is non-numeric

### ISSUE THREAD

**Issue by cliffordp** [Freemius/wordpress-sdk#148] opened 2017-02-27 03:24 UTC
**Actual Behavior**:
 -  `What is the issue? (*)`
> Fatal error: Uncaught : Unknown error, please check GetResult(). thrown in /.../freemius/includes/class-freemius.php on line 2542

**Versions**: (*)
 -  `Freemius SDK Version:` 1.2.1.5
 -  `WordPress Version:` 4.7.2
 -  `PHP Version:` 5.5.24

**Plugin / Theme**: (*)
 -  ... coding it first before publishing to Freemius ... making sure it can work ... so putting a _non-numeric_ fake `id` in there is what's causing the issue
 -  `Freemius ID:`
  ** `x` or `1x` (anything non-numeric, not non-integer) throws this error
  ** but `1` and `1.2` fail gracefully

![image](https://cloud.githubusercontent.com/assets/1812179/23347634/38b091be-fc69-11e6-88e1-e2ac45b9d5e3.png)

**Comment by vovafeldman** [comment] 2018-03-18 13:46
@cliffordp unless I'm missing something, it should throw an exception by design. Closing this for now.

**Closed by vovafeldman** 2018-03-18 13:46 UTC
