### ISSUE TITLE
Contact form url field defaulting to full referrer url not root url.

### ISSUE THREAD

**Issue by danieliser** [Freemius/wordpress-sdk#21] opened 2016-01-27 02:50 UTC

**Comment by danieliser** [comment] 2016-01-27 02:54
Since it is shown in dashboard you could probably safely remove everything from /wp-admin on.

**Comment by vovafeldman** [comment] 2016-01-29 21:41
I just tested it on local environment and it looks like it does extracts the site's root URL. Please provide the following:

- Your environment's contact us full URL.
- Screenshot of the current URL shown in the contact us form.
- The expected URL in the contact us form.

**Comment by danieliser** [comment] 2016-01-30 00:22
**Environment:** Typical VVV install. Nothing fancy.
**Page URL: ** http://pm.dev/wp-admin/edit.php?post_type=popup&page=popup-maker-contact
**Form URL: **http://pm.dev/wp-admin/edit.php?post_type=popup&page=popup-maker-contact
**Expected URL:** http://pm.dev

![screenshot from 2016-01-29 19 18 49](https://cloud.githubusercontent.com/assets/847818/12691805/93fec4b0-c6bd-11e5-90d4-a9630ef75ad0.png)


Is it a localhost issue? I have set the correct IP addresses in the Freemius config.

**Comment by vovafeldman** [comment] 2016-01-30 17:59
- Can you check if the issue also occurs when you opted-in? 
- Can you give me a temporary admin access to investigate? (send it via email)

**Comment by danieliser** [comment] 2016-01-30 22:23
@vovafeldman Its a local install of VVV but I can optin again to try it.

**Comment by vovafeldman** [comment] 2016-01-30 23:11
So you confirm that the issue happens when the user is opted-in?

**Comment by danieliser** [comment] 2016-02-01 05:19
@vovafeldman - You are correct. What does that mean. Is there a reason that opting in allows you to get the root url correctly?

Not sure why it couldn't strip id down correctly still with a preg_replace( '"wp-admin\/.*/", "", $referrer );

**Comment by vovafeldman** [comment] 2016-02-01 16:53
I just wanted to make sure we are seeing the same bug :) Try it now, should be fixed.

**Comment by vovafeldman** [comment] 2016-02-04 15:45
@danieliser can you confirm the issue is fixed on your end?

**Closed** 2016-02-05 04:56 UTC
Labels: bug
